### PR TITLE
Migrate some complex docs content

### PR DESCRIPTION
**Pull request by davidjgoss**
### 🤔 What's changed?

- Documentation link in header now links to docs section in this site, not the old site
- Some documentation pages ported over from the Gherkin and Cucumber sections, including some React stuff to make the more complex needs work
- All languages we show code in are syntax highlighted

(Bear in mind this site is still not live; we are working towards parity with the current site at cucumber.io so we can smoothly swap at some future point.)

### ⚡️ What's your motivation? 

See https://github.com/cucumber/website/issues/11#issuecomment-2027322217

We wanted to try porting some docs content over to this repo to make sure we can adequately handle the more complex kinds of content. Specifically:

- [x] Gherkin localisation tables
- [x] Tabs for code samples in different languages
- [x] Sync of language choice to URL
- [x] Persistance of language choice across pages
- [x] Equivalent of "short codes" for language-specific wording (e.g. "method" vs "function" et al)
- [x] Syntax highlighting for all languages we show code in

### 🏷️ What kind of change is this?

- :book: Documentation (improvements without changing code)
- :zap: New feature (non-breaking change which adds new behaviour)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by davidjgoss** [comment]
This now includes a shortcode-style thing working with a MDX component like:

```markdown
A Step Definition is a <Term>stepdef-body</Term> with an
```

With some more work we should hopefully be able to make this a CommonMark directive like:

```markdown
A Step Definition is a :term[stepdef-body] with an
```

**Comment by mpkorstanje** [comment]
image

On https://deploy-preview-14--cucumber-site-new.netlify.app/docs/cucumber/step-definitions

**Comment by davidjgoss** [comment]
🤦 fixed!

**Comment by mpkorstanje** [comment]
Looks good. As a 1-to-1 replacement this will work.

It looks like it will not solve the problem where whole sections do not apply to a certain language, but we can solve that differently.

**Pull request merged**
